### ISSUE TITLE
Add a mechanism for user to toggle between adding an existing semantic file and creating a new one

### ISSUE THREAD

**Issue by sfc-gh-rblum** [Snowflake-Labs/semantic-model-generator#140] opened 2024-08-29 15:21 UTC
If a user chooses one path in the opening screen, they can't go back without restarting the app.

**Comment by sfc-gh-cnivera** [comment] 2024-08-29 19:03
Fully agree! I think this is a dupe of https://github.com/Snowflake-Labs/semantic-model-generator/issues/137, so gonna close and track in the former.

**Closed by sfc-gh-cnivera** 2024-08-29 19:03 UTC
