### ISSUE TITLE
Comma delimited value in field causing error with sample value generation

### ISSUE THREAD

**Issue by sfc-gh-rblum** [Snowflake-Labs/semantic-model-generator#170] opened 2024-10-09 15:44 UTC
When there is a comma delimited list within a field, sample value generation does not include single quotes, and the comma is causing an error.  

![image (22)](https://github.com/user-attachments/assets/a41852ba-c44e-4eec-a4dc-c9d0244891f2)
![Screenshot 2024-10-07 at 15 49 17](https://github.com/user-attachments/assets/4c5956db-ac16-42ca-9b6b-e9f8a91658cd)

The underlying data looks like this:

SKU_LIST
_____________
732995874532,733001156055
195608993509
91307046549

**Comment by sfc-gh-cnivera** [comment] 2024-10-15 21:25
Closing this for now because I was not able to reproduce the issue locally, it might be another issue with the model. Happy to reopen if necessary.

**Closed by sfc-gh-cnivera** 2024-10-15 21:25 UTC
Labels: bug, medium
